# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b793286c5ac47e613ce835c6afc315aa2359a4dc8ee2dfa51e37916cb2e8d03295832a2588ea553573647c7c6e1981accc0be5ac03456c406f874923bac321b5

test:
  secret_key_base: 6bae19fcb0b0f58ec599d3ddeaadbf52c36f0ec38b205b6f42975801ca83ff776dedd32f04003147a78ec98a8df6a1446edecc12d88ac2d1e9c5406a0da5ddab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
